#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Figlut.Aplex.Web.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="FiglutAplex")]
	public partial class DataModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    partial void InsertUserPermission(UserPermission instance);
    partial void UpdateUserPermission(UserPermission instance);
    partial void DeleteUserPermission(UserPermission instance);
    partial void InsertDeviceConfig(DeviceConfig instance);
    partial void UpdateDeviceConfig(DeviceConfig instance);
    partial void DeleteDeviceConfig(DeviceConfig instance);
    partial void InsertDeviceConfigAction(DeviceConfigAction instance);
    partial void UpdateDeviceConfigAction(DeviceConfigAction instance);
    partial void DeleteDeviceConfigAction(DeviceConfigAction instance);
    partial void InsertDevicePendingApproval(DevicePendingApproval instance);
    partial void UpdateDevicePendingApproval(DevicePendingApproval instance);
    partial void DeleteDevicePendingApproval(DevicePendingApproval instance);
    partial void InsertGlobalVariable(GlobalVariable instance);
    partial void UpdateGlobalVariable(GlobalVariable instance);
    partial void DeleteGlobalVariable(GlobalVariable instance);
    partial void InsertServerAction(ServerAction instance);
    partial void UpdateServerAction(ServerAction instance);
    partial void DeleteServerAction(ServerAction instance);
    partial void InsertServerError(ServerError instance);
    partial void UpdateServerError(ServerError instance);
    partial void DeleteServerError(ServerError instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertEmailAction(EmailAction instance);
    partial void UpdateEmailAction(EmailAction instance);
    partial void DeleteEmailAction(EmailAction instance);
    #endregion
		
		public DataModelDataContext() : 
				base(global::Figlut.Aplex.Web.Data.Properties.Settings.Default.FiglutAplexConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
		
		public System.Data.Linq.Table<UserPermission> UserPermissions
		{
			get
			{
				return this.GetTable<UserPermission>();
			}
		}
		
		public System.Data.Linq.Table<DeviceConfig> DeviceConfigs
		{
			get
			{
				return this.GetTable<DeviceConfig>();
			}
		}
		
		public System.Data.Linq.Table<DeviceConfigAction> DeviceConfigActions
		{
			get
			{
				return this.GetTable<DeviceConfigAction>();
			}
		}
		
		public System.Data.Linq.Table<DevicePendingApproval> DevicePendingApprovals
		{
			get
			{
				return this.GetTable<DevicePendingApproval>();
			}
		}
		
		public System.Data.Linq.Table<GlobalVariable> GlobalVariables
		{
			get
			{
				return this.GetTable<GlobalVariable>();
			}
		}
		
		public System.Data.Linq.Table<ServerAction> ServerActions
		{
			get
			{
				return this.GetTable<ServerAction>();
			}
		}
		
		public System.Data.Linq.Table<ServerError> ServerErrors
		{
			get
			{
				return this.GetTable<ServerError>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<EmailAction> EmailActions
		{
			get
			{
				return this.GetTable<EmailAction>();
			}
		}
	}
	
	[Table(Name="dbo.Customer")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _CustomerId;
		
		private string _CompanyName;
		
		private string _PhysicalAddress;
		
		private string _PostalAddress;
		
		private string _ContactName;
		
		private string _ContactNumber;
		
		private string _ContactEmail;
		
		private System.DateTime _DateCreated;
		
		private EntitySet<DeviceConfig> _DeviceConfigs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomerIdChanging(System.Guid value);
    partial void OnCustomerIdChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnPhysicalAddressChanging(string value);
    partial void OnPhysicalAddressChanged();
    partial void OnPostalAddressChanging(string value);
    partial void OnPostalAddressChanged();
    partial void OnContactNameChanging(string value);
    partial void OnContactNameChanged();
    partial void OnContactNumberChanging(string value);
    partial void OnContactNumberChanged();
    partial void OnContactEmailChanging(string value);
    partial void OnContactEmailChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    #endregion
		
		public Customer()
		{
			this._DeviceConfigs = new EntitySet<DeviceConfig>(new Action<DeviceConfig>(this.attach_DeviceConfigs), new Action<DeviceConfig>(this.detach_DeviceConfigs));
			OnCreated();
		}
		
		[Column(Storage="_CustomerId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					this.OnCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerId = value;
					this.SendPropertyChanged("CustomerId");
					this.OnCustomerIdChanged();
				}
			}
		}
		
		[Column(Storage="_CompanyName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[Column(Storage="_PhysicalAddress", DbType="VarChar(MAX)")]
		public string PhysicalAddress
		{
			get
			{
				return this._PhysicalAddress;
			}
			set
			{
				if ((this._PhysicalAddress != value))
				{
					this.OnPhysicalAddressChanging(value);
					this.SendPropertyChanging();
					this._PhysicalAddress = value;
					this.SendPropertyChanged("PhysicalAddress");
					this.OnPhysicalAddressChanged();
				}
			}
		}
		
		[Column(Storage="_PostalAddress", DbType="VarChar(MAX)")]
		public string PostalAddress
		{
			get
			{
				return this._PostalAddress;
			}
			set
			{
				if ((this._PostalAddress != value))
				{
					this.OnPostalAddressChanging(value);
					this.SendPropertyChanging();
					this._PostalAddress = value;
					this.SendPropertyChanged("PostalAddress");
					this.OnPostalAddressChanged();
				}
			}
		}
		
		[Column(Storage="_ContactName", DbType="VarChar(50)")]
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				if ((this._ContactName != value))
				{
					this.OnContactNameChanging(value);
					this.SendPropertyChanging();
					this._ContactName = value;
					this.SendPropertyChanged("ContactName");
					this.OnContactNameChanged();
				}
			}
		}
		
		[Column(Storage="_ContactNumber", DbType="VarChar(50)")]
		public string ContactNumber
		{
			get
			{
				return this._ContactNumber;
			}
			set
			{
				if ((this._ContactNumber != value))
				{
					this.OnContactNumberChanging(value);
					this.SendPropertyChanging();
					this._ContactNumber = value;
					this.SendPropertyChanged("ContactNumber");
					this.OnContactNumberChanged();
				}
			}
		}
		
		[Column(Storage="_ContactEmail", DbType="VarChar(100)")]
		public string ContactEmail
		{
			get
			{
				return this._ContactEmail;
			}
			set
			{
				if ((this._ContactEmail != value))
				{
					this.OnContactEmailChanging(value);
					this.SendPropertyChanging();
					this._ContactEmail = value;
					this.SendPropertyChanged("ContactEmail");
					this.OnContactEmailChanged();
				}
			}
		}
		
		[Column(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[Association(Name="Customer_DeviceConfig", Storage="_DeviceConfigs", ThisKey="CustomerId", OtherKey="CustomerId")]
		public EntitySet<DeviceConfig> DeviceConfigs
		{
			get
			{
				return this._DeviceConfigs;
			}
			set
			{
				this._DeviceConfigs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DeviceConfigs(DeviceConfig entity)
		{
			this.SendPropertyChanging();
			entity.Customer = this;
		}
		
		private void detach_DeviceConfigs(DeviceConfig entity)
		{
			this.SendPropertyChanging();
			entity.Customer = null;
		}
	}
	
	[Table(Name="dbo.UserPermission")]
	public partial class UserPermission : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _UserPermissionId;
		
		private string _PermissionName;
		
		private System.Guid _UserId;
		
		private System.DateTime _DateCreated;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserPermissionIdChanging(System.Guid value);
    partial void OnUserPermissionIdChanged();
    partial void OnPermissionNameChanging(string value);
    partial void OnPermissionNameChanged();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    #endregion
		
		public UserPermission()
		{
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[Column(Storage="_UserPermissionId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserPermissionId
		{
			get
			{
				return this._UserPermissionId;
			}
			set
			{
				if ((this._UserPermissionId != value))
				{
					this.OnUserPermissionIdChanging(value);
					this.SendPropertyChanging();
					this._UserPermissionId = value;
					this.SendPropertyChanged("UserPermissionId");
					this.OnUserPermissionIdChanged();
				}
			}
		}
		
		[Column(Storage="_PermissionName", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string PermissionName
		{
			get
			{
				return this._PermissionName;
			}
			set
			{
				if ((this._PermissionName != value))
				{
					this.OnPermissionNameChanging(value);
					this.SendPropertyChanging();
					this._PermissionName = value;
					this.SendPropertyChanged("PermissionName");
					this.OnPermissionNameChanged();
				}
			}
		}
		
		[Column(Storage="_UserId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[Column(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[Association(Name="User_UserPermission", Storage="_User", ThisKey="UserId", OtherKey="UserId", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		internal User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.UserPermissions.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.UserPermissions.Add(this);
						this._UserId = value.UserId;
					}
					else
					{
						this._UserId = default(System.Guid);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.DeviceConfig")]
	public partial class DeviceConfig : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _DeviceConfigId;
		
		private string _DeviceId;
		
		private string _ApplicationName;
		
		private string _ApplicationWebServiceURL;
		
		private string _ApplicationReplicationWebServiceURL;
		
		private string _ClientConfigWebServiceURL;
		
		private System.Nullable<System.DateTime> _LicenseExpiryDate;
		
		private System.Nullable<System.DateTime> _LastConnectionDate;
		
		private System.Nullable<long> _ActionCount;
		
		private bool _NotifyOnInactivity;
		
		private System.Guid _CustomerId;
		
		private System.DateTime _DateCreated;
		
		private EntitySet<DeviceConfigAction> _DeviceConfigActions;
		
		private EntityRef<Customer> _Customer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDeviceConfigIdChanging(System.Guid value);
    partial void OnDeviceConfigIdChanged();
    partial void OnDeviceIdChanging(string value);
    partial void OnDeviceIdChanged();
    partial void OnApplicationNameChanging(string value);
    partial void OnApplicationNameChanged();
    partial void OnApplicationWebServiceURLChanging(string value);
    partial void OnApplicationWebServiceURLChanged();
    partial void OnApplicationReplicationWebServiceURLChanging(string value);
    partial void OnApplicationReplicationWebServiceURLChanged();
    partial void OnClientConfigWebServiceURLChanging(string value);
    partial void OnClientConfigWebServiceURLChanged();
    partial void OnLicenseExpiryDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLicenseExpiryDateChanged();
    partial void OnLastConnectionDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastConnectionDateChanged();
    partial void OnActionCountChanging(System.Nullable<long> value);
    partial void OnActionCountChanged();
    partial void OnNotifyOnInactivityChanging(bool value);
    partial void OnNotifyOnInactivityChanged();
    partial void OnCustomerIdChanging(System.Guid value);
    partial void OnCustomerIdChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    #endregion
		
		public DeviceConfig()
		{
			this._DeviceConfigActions = new EntitySet<DeviceConfigAction>(new Action<DeviceConfigAction>(this.attach_DeviceConfigActions), new Action<DeviceConfigAction>(this.detach_DeviceConfigActions));
			this._Customer = default(EntityRef<Customer>);
			OnCreated();
		}
		
		[Column(Storage="_DeviceConfigId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid DeviceConfigId
		{
			get
			{
				return this._DeviceConfigId;
			}
			set
			{
				if ((this._DeviceConfigId != value))
				{
					this.OnDeviceConfigIdChanging(value);
					this.SendPropertyChanging();
					this._DeviceConfigId = value;
					this.SendPropertyChanged("DeviceConfigId");
					this.OnDeviceConfigIdChanged();
				}
			}
		}
		
		[Column(Storage="_DeviceId", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string DeviceId
		{
			get
			{
				return this._DeviceId;
			}
			set
			{
				if ((this._DeviceId != value))
				{
					this.OnDeviceIdChanging(value);
					this.SendPropertyChanging();
					this._DeviceId = value;
					this.SendPropertyChanged("DeviceId");
					this.OnDeviceIdChanged();
				}
			}
		}
		
		[Column(Storage="_ApplicationName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ApplicationName
		{
			get
			{
				return this._ApplicationName;
			}
			set
			{
				if ((this._ApplicationName != value))
				{
					this.OnApplicationNameChanging(value);
					this.SendPropertyChanging();
					this._ApplicationName = value;
					this.SendPropertyChanged("ApplicationName");
					this.OnApplicationNameChanged();
				}
			}
		}
		
		[Column(Storage="_ApplicationWebServiceURL", DbType="VarChar(500)")]
		public string ApplicationWebServiceURL
		{
			get
			{
				return this._ApplicationWebServiceURL;
			}
			set
			{
				if ((this._ApplicationWebServiceURL != value))
				{
					this.OnApplicationWebServiceURLChanging(value);
					this.SendPropertyChanging();
					this._ApplicationWebServiceURL = value;
					this.SendPropertyChanged("ApplicationWebServiceURL");
					this.OnApplicationWebServiceURLChanged();
				}
			}
		}
		
		[Column(Storage="_ApplicationReplicationWebServiceURL", DbType="VarChar(500)")]
		public string ApplicationReplicationWebServiceURL
		{
			get
			{
				return this._ApplicationReplicationWebServiceURL;
			}
			set
			{
				if ((this._ApplicationReplicationWebServiceURL != value))
				{
					this.OnApplicationReplicationWebServiceURLChanging(value);
					this.SendPropertyChanging();
					this._ApplicationReplicationWebServiceURL = value;
					this.SendPropertyChanged("ApplicationReplicationWebServiceURL");
					this.OnApplicationReplicationWebServiceURLChanged();
				}
			}
		}
		
		[Column(Storage="_ClientConfigWebServiceURL", DbType="VarChar(500)")]
		public string ClientConfigWebServiceURL
		{
			get
			{
				return this._ClientConfigWebServiceURL;
			}
			set
			{
				if ((this._ClientConfigWebServiceURL != value))
				{
					this.OnClientConfigWebServiceURLChanging(value);
					this.SendPropertyChanging();
					this._ClientConfigWebServiceURL = value;
					this.SendPropertyChanged("ClientConfigWebServiceURL");
					this.OnClientConfigWebServiceURLChanged();
				}
			}
		}
		
		[Column(Storage="_LicenseExpiryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LicenseExpiryDate
		{
			get
			{
				return this._LicenseExpiryDate;
			}
			set
			{
				if ((this._LicenseExpiryDate != value))
				{
					this.OnLicenseExpiryDateChanging(value);
					this.SendPropertyChanging();
					this._LicenseExpiryDate = value;
					this.SendPropertyChanged("LicenseExpiryDate");
					this.OnLicenseExpiryDateChanged();
				}
			}
		}
		
		[Column(Storage="_LastConnectionDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastConnectionDate
		{
			get
			{
				return this._LastConnectionDate;
			}
			set
			{
				if ((this._LastConnectionDate != value))
				{
					this.OnLastConnectionDateChanging(value);
					this.SendPropertyChanging();
					this._LastConnectionDate = value;
					this.SendPropertyChanged("LastConnectionDate");
					this.OnLastConnectionDateChanged();
				}
			}
		}
		
		[Column(Storage="_ActionCount", DbType="BigInt")]
		public System.Nullable<long> ActionCount
		{
			get
			{
				return this._ActionCount;
			}
			set
			{
				if ((this._ActionCount != value))
				{
					this.OnActionCountChanging(value);
					this.SendPropertyChanging();
					this._ActionCount = value;
					this.SendPropertyChanged("ActionCount");
					this.OnActionCountChanged();
				}
			}
		}
		
		[Column(Storage="_NotifyOnInactivity", DbType="Bit NOT NULL")]
		public bool NotifyOnInactivity
		{
			get
			{
				return this._NotifyOnInactivity;
			}
			set
			{
				if ((this._NotifyOnInactivity != value))
				{
					this.OnNotifyOnInactivityChanging(value);
					this.SendPropertyChanging();
					this._NotifyOnInactivity = value;
					this.SendPropertyChanged("NotifyOnInactivity");
					this.OnNotifyOnInactivityChanged();
				}
			}
		}
		
		[Column(Storage="_CustomerId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid CustomerId
		{
			get
			{
				return this._CustomerId;
			}
			set
			{
				if ((this._CustomerId != value))
				{
					if (this._Customer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCustomerIdChanging(value);
					this.SendPropertyChanging();
					this._CustomerId = value;
					this.SendPropertyChanged("CustomerId");
					this.OnCustomerIdChanged();
				}
			}
		}
		
		[Column(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[Association(Name="DeviceConfig_DeviceConfigAction", Storage="_DeviceConfigActions", ThisKey="DeviceConfigId", OtherKey="DeviceConfigId")]
		public EntitySet<DeviceConfigAction> DeviceConfigActions
		{
			get
			{
				return this._DeviceConfigActions;
			}
			set
			{
				this._DeviceConfigActions.Assign(value);
			}
		}
		
		[Association(Name="Customer_DeviceConfig", Storage="_Customer", ThisKey="CustomerId", OtherKey="CustomerId", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		internal Customer Customer
		{
			get
			{
				return this._Customer.Entity;
			}
			set
			{
				Customer previousValue = this._Customer.Entity;
				if (((previousValue != value) 
							|| (this._Customer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Customer.Entity = null;
						previousValue.DeviceConfigs.Remove(this);
					}
					this._Customer.Entity = value;
					if ((value != null))
					{
						value.DeviceConfigs.Add(this);
						this._CustomerId = value.CustomerId;
					}
					else
					{
						this._CustomerId = default(System.Guid);
					}
					this.SendPropertyChanged("Customer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DeviceConfigActions(DeviceConfigAction entity)
		{
			this.SendPropertyChanging();
			entity.DeviceConfig = this;
		}
		
		private void detach_DeviceConfigActions(DeviceConfigAction entity)
		{
			this.SendPropertyChanging();
			entity.DeviceConfig = null;
		}
	}
	
	[Table(Name="dbo.DeviceConfigAction")]
	public partial class DeviceConfigAction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _DeviceConfigActionId;
		
		private System.DateTime _DateCreated;
		
		private string _Function;
		
		private string _DeviceId;
		
		private string _ApplicationName;
		
		private string _CustomerCompanyName;
		
		private string _Tag;
		
		private System.Nullable<System.Guid> _DeviceConfigId;
		
		private EntityRef<DeviceConfig> _DeviceConfig;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDeviceConfigActionIdChanging(System.Guid value);
    partial void OnDeviceConfigActionIdChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnFunctionChanging(string value);
    partial void OnFunctionChanged();
    partial void OnDeviceIdChanging(string value);
    partial void OnDeviceIdChanged();
    partial void OnApplicationNameChanging(string value);
    partial void OnApplicationNameChanged();
    partial void OnCustomerCompanyNameChanging(string value);
    partial void OnCustomerCompanyNameChanged();
    partial void OnTagChanging(string value);
    partial void OnTagChanged();
    partial void OnDeviceConfigIdChanging(System.Nullable<System.Guid> value);
    partial void OnDeviceConfigIdChanged();
    #endregion
		
		public DeviceConfigAction()
		{
			this._DeviceConfig = default(EntityRef<DeviceConfig>);
			OnCreated();
		}
		
		[Column(Storage="_DeviceConfigActionId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid DeviceConfigActionId
		{
			get
			{
				return this._DeviceConfigActionId;
			}
			set
			{
				if ((this._DeviceConfigActionId != value))
				{
					this.OnDeviceConfigActionIdChanging(value);
					this.SendPropertyChanging();
					this._DeviceConfigActionId = value;
					this.SendPropertyChanged("DeviceConfigActionId");
					this.OnDeviceConfigActionIdChanged();
				}
			}
		}
		
		[Column(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[Column(Name="[Function]", Storage="_Function", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Function
		{
			get
			{
				return this._Function;
			}
			set
			{
				if ((this._Function != value))
				{
					this.OnFunctionChanging(value);
					this.SendPropertyChanging();
					this._Function = value;
					this.SendPropertyChanged("Function");
					this.OnFunctionChanged();
				}
			}
		}
		
		[Column(Storage="_DeviceId", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string DeviceId
		{
			get
			{
				return this._DeviceId;
			}
			set
			{
				if ((this._DeviceId != value))
				{
					this.OnDeviceIdChanging(value);
					this.SendPropertyChanging();
					this._DeviceId = value;
					this.SendPropertyChanged("DeviceId");
					this.OnDeviceIdChanged();
				}
			}
		}
		
		[Column(Storage="_ApplicationName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ApplicationName
		{
			get
			{
				return this._ApplicationName;
			}
			set
			{
				if ((this._ApplicationName != value))
				{
					this.OnApplicationNameChanging(value);
					this.SendPropertyChanging();
					this._ApplicationName = value;
					this.SendPropertyChanged("ApplicationName");
					this.OnApplicationNameChanged();
				}
			}
		}
		
		[Column(Storage="_CustomerCompanyName", DbType="VarChar(100)")]
		public string CustomerCompanyName
		{
			get
			{
				return this._CustomerCompanyName;
			}
			set
			{
				if ((this._CustomerCompanyName != value))
				{
					this.OnCustomerCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CustomerCompanyName = value;
					this.SendPropertyChanged("CustomerCompanyName");
					this.OnCustomerCompanyNameChanged();
				}
			}
		}
		
		[Column(Storage="_Tag", DbType="VarChar(MAX)")]
		public string Tag
		{
			get
			{
				return this._Tag;
			}
			set
			{
				if ((this._Tag != value))
				{
					this.OnTagChanging(value);
					this.SendPropertyChanging();
					this._Tag = value;
					this.SendPropertyChanged("Tag");
					this.OnTagChanged();
				}
			}
		}
		
		[Column(Storage="_DeviceConfigId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> DeviceConfigId
		{
			get
			{
				return this._DeviceConfigId;
			}
			set
			{
				if ((this._DeviceConfigId != value))
				{
					if (this._DeviceConfig.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDeviceConfigIdChanging(value);
					this.SendPropertyChanging();
					this._DeviceConfigId = value;
					this.SendPropertyChanged("DeviceConfigId");
					this.OnDeviceConfigIdChanged();
				}
			}
		}
		
		[Association(Name="DeviceConfig_DeviceConfigAction", Storage="_DeviceConfig", ThisKey="DeviceConfigId", OtherKey="DeviceConfigId", IsForeignKey=true, DeleteRule="SET NULL")]
		internal DeviceConfig DeviceConfig
		{
			get
			{
				return this._DeviceConfig.Entity;
			}
			set
			{
				DeviceConfig previousValue = this._DeviceConfig.Entity;
				if (((previousValue != value) 
							|| (this._DeviceConfig.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DeviceConfig.Entity = null;
						previousValue.DeviceConfigActions.Remove(this);
					}
					this._DeviceConfig.Entity = value;
					if ((value != null))
					{
						value.DeviceConfigActions.Add(this);
						this._DeviceConfigId = value.DeviceConfigId;
					}
					else
					{
						this._DeviceConfigId = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("DeviceConfig");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.DevicePendingApproval")]
	public partial class DevicePendingApproval : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _DevicePendingApprovalId;
		
		private string _DeviceId;
		
		private string _ApplicationName;
		
		private System.DateTime _DateCreated;
		
		private System.DateTime _LatestAttemptDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDevicePendingApprovalIdChanging(System.Guid value);
    partial void OnDevicePendingApprovalIdChanged();
    partial void OnDeviceIdChanging(string value);
    partial void OnDeviceIdChanged();
    partial void OnApplicationNameChanging(string value);
    partial void OnApplicationNameChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnLatestAttemptDateChanging(System.DateTime value);
    partial void OnLatestAttemptDateChanged();
    #endregion
		
		public DevicePendingApproval()
		{
			OnCreated();
		}
		
		[Column(Storage="_DevicePendingApprovalId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid DevicePendingApprovalId
		{
			get
			{
				return this._DevicePendingApprovalId;
			}
			set
			{
				if ((this._DevicePendingApprovalId != value))
				{
					this.OnDevicePendingApprovalIdChanging(value);
					this.SendPropertyChanging();
					this._DevicePendingApprovalId = value;
					this.SendPropertyChanged("DevicePendingApprovalId");
					this.OnDevicePendingApprovalIdChanged();
				}
			}
		}
		
		[Column(Storage="_DeviceId", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string DeviceId
		{
			get
			{
				return this._DeviceId;
			}
			set
			{
				if ((this._DeviceId != value))
				{
					this.OnDeviceIdChanging(value);
					this.SendPropertyChanging();
					this._DeviceId = value;
					this.SendPropertyChanged("DeviceId");
					this.OnDeviceIdChanged();
				}
			}
		}
		
		[Column(Storage="_ApplicationName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ApplicationName
		{
			get
			{
				return this._ApplicationName;
			}
			set
			{
				if ((this._ApplicationName != value))
				{
					this.OnApplicationNameChanging(value);
					this.SendPropertyChanging();
					this._ApplicationName = value;
					this.SendPropertyChanged("ApplicationName");
					this.OnApplicationNameChanged();
				}
			}
		}
		
		[Column(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[Column(Storage="_LatestAttemptDate", DbType="DateTime NOT NULL")]
		public System.DateTime LatestAttemptDate
		{
			get
			{
				return this._LatestAttemptDate;
			}
			set
			{
				if ((this._LatestAttemptDate != value))
				{
					this.OnLatestAttemptDateChanging(value);
					this.SendPropertyChanging();
					this._LatestAttemptDate = value;
					this.SendPropertyChanged("LatestAttemptDate");
					this.OnLatestAttemptDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.GlobalVariable")]
	public partial class GlobalVariable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _GlobalVariableId;
		
		private string _VariableName;
		
		private string _VariableValue;
		
		private System.DateTime _DateCreated;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGlobalVariableIdChanging(System.Guid value);
    partial void OnGlobalVariableIdChanged();
    partial void OnVariableNameChanging(string value);
    partial void OnVariableNameChanged();
    partial void OnVariableValueChanging(string value);
    partial void OnVariableValueChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    #endregion
		
		public GlobalVariable()
		{
			OnCreated();
		}
		
		[Column(Storage="_GlobalVariableId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid GlobalVariableId
		{
			get
			{
				return this._GlobalVariableId;
			}
			set
			{
				if ((this._GlobalVariableId != value))
				{
					this.OnGlobalVariableIdChanging(value);
					this.SendPropertyChanging();
					this._GlobalVariableId = value;
					this.SendPropertyChanged("GlobalVariableId");
					this.OnGlobalVariableIdChanged();
				}
			}
		}
		
		[Column(Storage="_VariableName", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string VariableName
		{
			get
			{
				return this._VariableName;
			}
			set
			{
				if ((this._VariableName != value))
				{
					this.OnVariableNameChanging(value);
					this.SendPropertyChanging();
					this._VariableName = value;
					this.SendPropertyChanged("VariableName");
					this.OnVariableNameChanged();
				}
			}
		}
		
		[Column(Storage="_VariableValue", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string VariableValue
		{
			get
			{
				return this._VariableValue;
			}
			set
			{
				if ((this._VariableValue != value))
				{
					this.OnVariableValueChanging(value);
					this.SendPropertyChanging();
					this._VariableValue = value;
					this.SendPropertyChanged("VariableValue");
					this.OnVariableValueChanged();
				}
			}
		}
		
		[Column(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.ServerAction")]
	public partial class ServerAction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ServerActionId;
		
		private System.DateTime _DateCreated;
		
		private string _Function;
		
		private System.Nullable<System.Guid> _UserId;
		
		private string _UserName;
		
		private string _EntityChanged;
		
		private string _FieldChanged;
		
		private string _OriginalValue;
		
		private string _NewValue;
		
		private string _Comments;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnServerActionIdChanging(int value);
    partial void OnServerActionIdChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnFunctionChanging(string value);
    partial void OnFunctionChanged();
    partial void OnUserIdChanging(System.Nullable<System.Guid> value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnEntityChangedChanging(string value);
    partial void OnEntityChangedChanged();
    partial void OnFieldChangedChanging(string value);
    partial void OnFieldChangedChanged();
    partial void OnOriginalValueChanging(string value);
    partial void OnOriginalValueChanged();
    partial void OnNewValueChanging(string value);
    partial void OnNewValueChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    #endregion
		
		public ServerAction()
		{
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[Column(Storage="_ServerActionId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ServerActionId
		{
			get
			{
				return this._ServerActionId;
			}
			set
			{
				if ((this._ServerActionId != value))
				{
					this.OnServerActionIdChanging(value);
					this.SendPropertyChanging();
					this._ServerActionId = value;
					this.SendPropertyChanged("ServerActionId");
					this.OnServerActionIdChanged();
				}
			}
		}
		
		[Column(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[Column(Name="[Function]", Storage="_Function", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Function
		{
			get
			{
				return this._Function;
			}
			set
			{
				if ((this._Function != value))
				{
					this.OnFunctionChanging(value);
					this.SendPropertyChanging();
					this._Function = value;
					this.SendPropertyChanged("Function");
					this.OnFunctionChanged();
				}
			}
		}
		
		[Column(Storage="_UserId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[Column(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[Column(Storage="_EntityChanged", DbType="VarChar(50)")]
		public string EntityChanged
		{
			get
			{
				return this._EntityChanged;
			}
			set
			{
				if ((this._EntityChanged != value))
				{
					this.OnEntityChangedChanging(value);
					this.SendPropertyChanging();
					this._EntityChanged = value;
					this.SendPropertyChanged("EntityChanged");
					this.OnEntityChangedChanged();
				}
			}
		}
		
		[Column(Storage="_FieldChanged", DbType="VarChar(50)")]
		public string FieldChanged
		{
			get
			{
				return this._FieldChanged;
			}
			set
			{
				if ((this._FieldChanged != value))
				{
					this.OnFieldChangedChanging(value);
					this.SendPropertyChanging();
					this._FieldChanged = value;
					this.SendPropertyChanged("FieldChanged");
					this.OnFieldChangedChanged();
				}
			}
		}
		
		[Column(Storage="_OriginalValue", DbType="VarChar(250)")]
		public string OriginalValue
		{
			get
			{
				return this._OriginalValue;
			}
			set
			{
				if ((this._OriginalValue != value))
				{
					this.OnOriginalValueChanging(value);
					this.SendPropertyChanging();
					this._OriginalValue = value;
					this.SendPropertyChanged("OriginalValue");
					this.OnOriginalValueChanged();
				}
			}
		}
		
		[Column(Storage="_NewValue", DbType="VarChar(250)")]
		public string NewValue
		{
			get
			{
				return this._NewValue;
			}
			set
			{
				if ((this._NewValue != value))
				{
					this.OnNewValueChanging(value);
					this.SendPropertyChanging();
					this._NewValue = value;
					this.SendPropertyChanged("NewValue");
					this.OnNewValueChanged();
				}
			}
		}
		
		[Column(Storage="_Comments", DbType="VarChar(250)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this.OnCommentsChanging(value);
					this.SendPropertyChanging();
					this._Comments = value;
					this.SendPropertyChanged("Comments");
					this.OnCommentsChanged();
				}
			}
		}
		
		[Association(Name="User_ServerAction", Storage="_User", ThisKey="UserId", OtherKey="UserId", IsForeignKey=true, DeleteRule="SET NULL")]
		internal User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.ServerActions.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.ServerActions.Add(this);
						this._UserId = value.UserId;
					}
					else
					{
						this._UserId = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.ServerError")]
	public partial class ServerError : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ServerErrorId;
		
		private System.DateTime _DateCreated;
		
		private string _ErrorMessage;
		
		private System.Nullable<System.Guid> _UserId;
		
		private string _UserName;
		
		private string _Comments;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnServerErrorIdChanging(int value);
    partial void OnServerErrorIdChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnErrorMessageChanging(string value);
    partial void OnErrorMessageChanged();
    partial void OnUserIdChanging(System.Nullable<System.Guid> value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    #endregion
		
		public ServerError()
		{
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[Column(Storage="_ServerErrorId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ServerErrorId
		{
			get
			{
				return this._ServerErrorId;
			}
			set
			{
				if ((this._ServerErrorId != value))
				{
					this.OnServerErrorIdChanging(value);
					this.SendPropertyChanging();
					this._ServerErrorId = value;
					this.SendPropertyChanged("ServerErrorId");
					this.OnServerErrorIdChanged();
				}
			}
		}
		
		[Column(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[Column(Storage="_ErrorMessage", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string ErrorMessage
		{
			get
			{
				return this._ErrorMessage;
			}
			set
			{
				if ((this._ErrorMessage != value))
				{
					this.OnErrorMessageChanging(value);
					this.SendPropertyChanging();
					this._ErrorMessage = value;
					this.SendPropertyChanged("ErrorMessage");
					this.OnErrorMessageChanged();
				}
			}
		}
		
		[Column(Storage="_UserId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[Column(Storage="_UserName", DbType="VarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[Column(Storage="_Comments", DbType="VarChar(250)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this.OnCommentsChanging(value);
					this.SendPropertyChanging();
					this._Comments = value;
					this.SendPropertyChanged("Comments");
					this.OnCommentsChanged();
				}
			}
		}
		
		[Association(Name="User_ServerError", Storage="_User", ThisKey="UserId", OtherKey="UserId", IsForeignKey=true, DeleteRule="SET NULL")]
		internal User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.ServerErrors.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.ServerErrors.Add(this);
						this._UserId = value.UserId;
					}
					else
					{
						this._UserId = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _UserId;
		
		private string _UserName;
		
		private string _Password;
		
		private int _RoleId;
		
		private string _Name;
		
		private string _Surname;
		
		private string _Email;
		
		private string _Address;
		
		private System.DateTime _DateCreated;
		
		private string _Phone;
		
		private bool _EmailNotifications;
		
		private EntitySet<UserPermission> _UserPermissions;
		
		private EntitySet<ServerAction> _ServerActions;
		
		private EntitySet<ServerError> _ServerErrors;
		
		private EntitySet<EmailAction> _EmailActions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnRoleIdChanging(int value);
    partial void OnRoleIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnEmailNotificationsChanging(bool value);
    partial void OnEmailNotificationsChanged();
    #endregion
		
		public User()
		{
			this._UserPermissions = new EntitySet<UserPermission>(new Action<UserPermission>(this.attach_UserPermissions), new Action<UserPermission>(this.detach_UserPermissions));
			this._ServerActions = new EntitySet<ServerAction>(new Action<ServerAction>(this.attach_ServerActions), new Action<ServerAction>(this.detach_ServerActions));
			this._ServerErrors = new EntitySet<ServerError>(new Action<ServerError>(this.attach_ServerErrors), new Action<ServerError>(this.detach_ServerErrors));
			this._EmailActions = new EntitySet<EmailAction>(new Action<EmailAction>(this.attach_EmailActions), new Action<EmailAction>(this.detach_EmailActions));
			OnCreated();
		}
		
		[Column(Storage="_UserId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[Column(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[Column(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[Column(Storage="_RoleId", DbType="Int NOT NULL")]
		public int RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					this.OnRoleIdChanging(value);
					this.SendPropertyChanging();
					this._RoleId = value;
					this.SendPropertyChanged("RoleId");
					this.OnRoleIdChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Column(Storage="_Surname", DbType="VarChar(50)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[Column(Storage="_Email", DbType="VarChar(250)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[Column(Storage="_Address", DbType="VarChar(MAX)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[Column(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[Column(Storage="_Phone", DbType="VarChar(50)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[Column(Storage="_EmailNotifications", DbType="Bit NOT NULL")]
		public bool EmailNotifications
		{
			get
			{
				return this._EmailNotifications;
			}
			set
			{
				if ((this._EmailNotifications != value))
				{
					this.OnEmailNotificationsChanging(value);
					this.SendPropertyChanging();
					this._EmailNotifications = value;
					this.SendPropertyChanged("EmailNotifications");
					this.OnEmailNotificationsChanged();
				}
			}
		}
		
		[Association(Name="User_UserPermission", Storage="_UserPermissions", ThisKey="UserId", OtherKey="UserId")]
		public EntitySet<UserPermission> UserPermissions
		{
			get
			{
				return this._UserPermissions;
			}
			set
			{
				this._UserPermissions.Assign(value);
			}
		}
		
		[Association(Name="User_ServerAction", Storage="_ServerActions", ThisKey="UserId", OtherKey="UserId")]
		public EntitySet<ServerAction> ServerActions
		{
			get
			{
				return this._ServerActions;
			}
			set
			{
				this._ServerActions.Assign(value);
			}
		}
		
		[Association(Name="User_ServerError", Storage="_ServerErrors", ThisKey="UserId", OtherKey="UserId")]
		public EntitySet<ServerError> ServerErrors
		{
			get
			{
				return this._ServerErrors;
			}
			set
			{
				this._ServerErrors.Assign(value);
			}
		}
		
		[Association(Name="User_EmailAction", Storage="_EmailActions", ThisKey="UserId", OtherKey="UserId")]
		public EntitySet<EmailAction> EmailActions
		{
			get
			{
				return this._EmailActions;
			}
			set
			{
				this._EmailActions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UserPermissions(UserPermission entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_UserPermissions(UserPermission entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_ServerActions(ServerAction entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_ServerActions(ServerAction entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_ServerErrors(ServerError entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_ServerErrors(ServerError entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
		
		private void attach_EmailActions(EmailAction entity)
		{
			this.SendPropertyChanging();
			entity.User = this;
		}
		
		private void detach_EmailActions(EmailAction entity)
		{
			this.SendPropertyChanging();
			entity.User = null;
		}
	}
	
	[Table(Name="dbo.EmailAction")]
	public partial class EmailAction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _EmailActionId;
		
		private string _ToEmailAddress;
		
		private string _FromEmailAddress;
		
		private string _Subject;
		
		private string _Body;
		
		private System.Nullable<System.Guid> _UserId;
		
		private System.DateTime _DateCreated;
		
		private EntityRef<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmailActionIdChanging(System.Guid value);
    partial void OnEmailActionIdChanged();
    partial void OnToEmailAddressChanging(string value);
    partial void OnToEmailAddressChanged();
    partial void OnFromEmailAddressChanging(string value);
    partial void OnFromEmailAddressChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnBodyChanging(string value);
    partial void OnBodyChanged();
    partial void OnUserIdChanging(System.Nullable<System.Guid> value);
    partial void OnUserIdChanged();
    partial void OnDateCreatedChanging(System.DateTime value);
    partial void OnDateCreatedChanged();
    #endregion
		
		public EmailAction()
		{
			this._User = default(EntityRef<User>);
			OnCreated();
		}
		
		[Column(Storage="_EmailActionId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid EmailActionId
		{
			get
			{
				return this._EmailActionId;
			}
			set
			{
				if ((this._EmailActionId != value))
				{
					this.OnEmailActionIdChanging(value);
					this.SendPropertyChanging();
					this._EmailActionId = value;
					this.SendPropertyChanged("EmailActionId");
					this.OnEmailActionIdChanged();
				}
			}
		}
		
		[Column(Storage="_ToEmailAddress", DbType="VarChar(250)")]
		public string ToEmailAddress
		{
			get
			{
				return this._ToEmailAddress;
			}
			set
			{
				if ((this._ToEmailAddress != value))
				{
					this.OnToEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._ToEmailAddress = value;
					this.SendPropertyChanged("ToEmailAddress");
					this.OnToEmailAddressChanged();
				}
			}
		}
		
		[Column(Storage="_FromEmailAddress", DbType="VarChar(250)")]
		public string FromEmailAddress
		{
			get
			{
				return this._FromEmailAddress;
			}
			set
			{
				if ((this._FromEmailAddress != value))
				{
					this.OnFromEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._FromEmailAddress = value;
					this.SendPropertyChanged("FromEmailAddress");
					this.OnFromEmailAddressChanged();
				}
			}
		}
		
		[Column(Storage="_Subject", DbType="VarChar(MAX)")]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this.OnSubjectChanging(value);
					this.SendPropertyChanging();
					this._Subject = value;
					this.SendPropertyChanged("Subject");
					this.OnSubjectChanged();
				}
			}
		}
		
		[Column(Storage="_Body", DbType="VarChar(MAX)")]
		public string Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				if ((this._Body != value))
				{
					this.OnBodyChanging(value);
					this.SendPropertyChanging();
					this._Body = value;
					this.SendPropertyChanged("Body");
					this.OnBodyChanged();
				}
			}
		}
		
		[Column(Storage="_UserId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._User.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[Column(Storage="_DateCreated", DbType="DateTime NOT NULL")]
		public System.DateTime DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[Association(Name="User_EmailAction", Storage="_User", ThisKey="UserId", OtherKey="UserId", IsForeignKey=true, DeleteRule="SET NULL")]
		internal User User
		{
			get
			{
				return this._User.Entity;
			}
			set
			{
				User previousValue = this._User.Entity;
				if (((previousValue != value) 
							|| (this._User.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User.Entity = null;
						previousValue.EmailActions.Remove(this);
					}
					this._User.Entity = value;
					if ((value != null))
					{
						value.EmailActions.Add(this);
						this._UserId = value.UserId;
					}
					else
					{
						this._UserId = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("User");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
